#! /bin/sh
M2=$1
TMP=multiprocess-input-temp
rm -f $TMP.out
exec 3>&1
exec >$TMP.m2
while true
do read x
   ret=$?
   if [ $ret != 0 -o "$x" = exit ]
   then echo "$x"
	exec >&2
	echo running
	$M2 -q --stop eg.m2 <$TMP.m2 >>$TMP.out || exit 1
	if [ $ret != 0 ]
	then break
	fi
	exec >$TMP.m2
   else echo "$x"
   fi
done
rm -f $TMP.m2
exec 1>&3
cat $TMP.out
rm -f $TMP.out

